Automatically determine release, and create if neccessary.
- if .0, create Formula and update alias symlink
- otherwise, require it to exist

Test Plan:

```
$ ./build-release.sh 4.17.1
++ mktemp -d
+ DLDIR=/var/folders/m0/zhq4ljv51s54qjf274hw_0pc0000gn/T/tmp.TO9Sk5VG
++ awk -F / '/^  url/{print $NF}' /Users/fredemmott/code/homebrew-hhvm/Formula/hhvm-4.17.rb
++ gsed 's/^.\+-\([0-9].\+\)\.tar.\+/\1/'
+ PREV_VERSION=4.17.1
+ aws s3 cp s3://hhvm-scratch/hhvm-4.17.1.tar.gz /var/folders/m0/zhq4ljv51s54qjf274hw_0pc0000gn/T/tmp.TO9Sk5VG/
download: s3://hhvm-scratch/hhvm-4.17.1.tar.gz to ../../../../var/folders/m0/zhq4ljv51s54qjf274hw_0pc0000gn/T/tmp.TO9Sk5VG/hhvm-4.17.1.tar.gz
+ aws s3 cp s3://hhvm-scratch/hhvm-4.17.1.tar.gz.sig /var/folders/m0/zhq4ljv51s54qjf274hw_0pc0000gn/T/tmp.TO9Sk5VG/
download: s3://hhvm-scratch/hhvm-4.17.1.tar.gz.sig to ../../../../var/folders/m0/zhq4ljv51s54qjf274hw_0pc0000gn/T/tmp.TO9Sk5VG/hhvm-4.17.1.tar.gz.sig
+ gpg --verify /var/folders/m0/zhq4ljv51s54qjf274hw_0pc0000gn/T/tmp.TO9Sk5VG/hhvm-4.17.1.tar.gz.sig
gpg: assuming signed data in '/var/folders/m0/zhq4ljv51s54qjf274hw_0pc0000gn/T/tmp.TO9Sk5VG/hhvm-4.17.1.tar.gz'
gpg: Signature made Wed Aug  7 15:17:03 2019 PDT
gpg:                using RSA key B4112585D386EB94
gpg: key B4112585D386EB94: 1 signature not checked due to a missing key
gpg: key B4112585D386EB94: public key "HHVM Package Signing <opensource+hhvm@fb.com>" imported
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   1  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   1  signed:   0  trust: 1-, 0q, 0n, 0m, 0f, 0u
gpg: Total number processed: 1
gpg:               imported: 1
gpg: Good signature from "HHVM Package Signing <opensource+hhvm@fb.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 0583 41C6 8FC8 DE60 17D7  75A1 B411 2585 D386 EB94
++ openssl sha256 /var/folders/m0/zhq4ljv51s54qjf274hw_0pc0000gn/T/tmp.TO9Sk5VG/hhvm-4.17.1.tar.gz
++ awk '{print $NF}'
+ SHA=2464b4dc19e77f1b6bb30b99e3e315f0c630ffa47703032294b78edbc4956e59
+ '[' 4.17.1 = 4.17.1 ']'
++ awk '/^  revision /{print $2}' /Users/fredemmott/code/homebrew-hhvm/Formula/hhvm-4.17.rb
+ PREVIOUS_REVISION=0
+ REVISION=1
+ gsed -i 's,^  revision [0-9]\+,  revision 1,' /Users/fredemmott/code/homebrew-hhvm/Formula/hhvm-4.17.rb
+ brew list
+ grep hhvm
+ xargs brew uninstall --force
Uninstalling hhvm-4.10... (1,150 files, 297.1MB)
Uninstalling hhvm-4.12... (1,150 files, 281.1MB)
Uninstalling hhvm-4.17... (1,154 files, 298.9MB)
+ rm -f '*.bottle' '*.json'
+ brew upgrade
+ brew install --bottle-arch=nehalem --build-bottle /Users/fredemmott/code/homebrew-hhvm/Formula/hhvm-4.17.rb
==> Installing dependencies for hhvm-4.17: autoconf, automake, cmake, double-conversion, dwarfutils, libelf, md5sha1sum and pkg-config
==> Installing hhvm-4.17 dependency: autoconf
^C
fredemmott-mm1:homebrew-hhvm fredemmott$ ./build-release.sh 4.18.0
++ mktemp -d
+ DLDIR=/var/folders/m0/zhq4ljv51s54qjf274hw_0pc0000gn/T/tmp.coH4OwlL
++ awk -F / '/^  url/{print $NF}' /Users/fredemmott/code/homebrew-hhvm/Formula/hhvm-4.18.rb
++ gsed 's/^.\+-\([0-9].\+\)\.tar.\+/\1/'
+ PREV_VERSION=2019.08.08
+ aws s3 cp s3://hhvm-scratch/hhvm-4.18.0.tar.gz /var/folders/m0/zhq4ljv51s54qjf274hw_0pc0000gn/T/tmp.coH4OwlL/
fatal error: An error occurred (404) when calling the HeadObject operation: Key "hhvm-4.18.0.tar.gz" does not exist
fredemmott-mm1:homebrew-hhvm fredemmott$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   Aliases/hhvm
	modified:   Formula/hhvm-4.17.rb
	modified:   build-release.sh

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	Formula/hhvm-4.18.rb

no changes added to commit (use "git add" and/or "git commit -a")
fredemmott-mm1:homebrew-hhvm fredemmott$ head Formula/hhvm-4.18.rb
class Hhvm418 < Formula
  desc "JIT compiler and runtime for the Hack language"
  homepage "http://hhvm.com/"
  head "https://github.com/facebook/hhvm.git"
  url "https://dl.hhvm.com/source/nightlies/hhvm-nightly-2019.08.08.tar.gz"
  sha256 "611794c57e48f58d99835caa17b581e0bcefdc5459bed6880874d963ad88a541"
  # package version - reset to 0 when HHVM version changes
  revision 0

  bottle do
fredemmott-mm1:homebrew-hhvm fredemmott$ git diff Aliases/hhvm
diff --git a/Aliases/hhvm b/Aliases/hhvm
index 65ff04f..eb6631d 120000
--- a/Aliases/hhvm
+++ b/Aliases/hhvm
@@ -1 +1 @@
-../Formula/hhvm-4.17.rb
\ No newline at end of file
+../Formula/hhvm-4.18.rb
\ No newline at end of file
fredemmott-mm1:homebrew-hhvm fredemmott$ head Aliases/hhvm
class Hhvm418 < Formula
  desc "JIT compiler and runtime for the Hack language"
  homepage "http://hhvm.com/"
  head "https://github.com/facebook/hhvm.git"
  url "https://dl.hhvm.com/source/nightlies/hhvm-nightly-2019.08.08.tar.gz"
  sha256 "611794c57e48f58d99835caa17b581e0bcefdc5459bed6880874d963ad88a541"
  # package version - reset to 0 when HHVM version changes
  revision 0

  bottle do
```